---
title: "Advent of Code 2020"
author: "Stephanie M Haas"
date: "12/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


#Day 1

##Part 1
```{r}
day1 <- read_csv("data/day1.csv")


total <- 2020
high_values <- day1 %>% filter(expense > total/2 & expense != iter)
low_values <- day1 %>% filter(expense < total/2 & expense != iter)
pair <- high_values %>% 
  mutate(search_value = total - expense) %>% 
    inner_join(low_values, by = c("search_value" = "expense"))
pair[1,1] * pair[1,2]
```

##Part 2

```{r}

first_value <- day1 %>% filter(expense <= 2020/2)

list <- lapply(first_value$expense, function(iter){
  total <- 2020 - iter
  high_values <- day1 %>% filter(expense > total/2 & expense != iter)
  low_values <- day1 %>% filter(expense < total/2 & expense != iter)
  pair <- high_values %>% 
      mutate(search_value = (expense - total) * -1) %>% 
      inner_join(low_values, by = c("search_value" = "expense"))
  return(iter * pair[1,1] * pair[1,2])
})



k = NA
i = 1
while(k = NA){
  iter <- first_value$expense[i]
  total <- 2020 - iter
  high_values <- day1 %>% filter(expense > total/2 & expense != iter)
  low_values <- day1 %>% filter(expense < total/2 & expense != iter)
  pair <- high_values %>% 
    mutate(search_value = total - expense) %>% 
    inner_join(low_values, by = c("search_value" = "expense"))
  k = iter * pair[1,1] * pair[1,2]
  i = i + 1
}
k

```

#Day 2

##Part 1

```{r}
day2 <- read_csv("data/day2.csv")

day2_split <- sapply(day2$value, strsplit, split = ": | |-")
day2_split <- do.call("rbind", day2_split)

colnames(day2_split) <- c("min", "max", "letter", "password")

day2_split <- as_tibble(day2_split) %>% 
  mutate(valid = NA,
         min = as.numeric(min),
         max = as.numeric(max)) %>% 
  rowid_to_column()

errors <- lapply(day2_split$rowid, function(row){
  code <- str_extract_all(day2_split$password[row], "[a-z]")
  code <- do.call("rbind", code)
  iter <- length(code[code == day2_split$letter[row]])
  if (iter >= day2_split$min[row] & iter <= day2_split$max[row]){

    return(1)

  }else{

    return(0)

  }
})

do.call("sum", errors)

```


##Part 2

```{r}

errors <- lapply(day2_split$rowid, function(row){
  code <- str_extract_all(day2_split$password[row], "[a-z]")
  code <- do.call("rbind", code)
  first <- code[day2_split$min[row]]
  second <- code[day2_split$max[row]]
  if (xor(first == day2_split$letter[row], second == day2_split$letter[row])){
    
    return(1)
    
  }else{
    
    return(0)
    
  }
})

do.call("sum", errors)


```


#Day 3

##Part 1

```{r}
day3 <- read_csv("data/day3.csv", col_names = "hill")

day3 <- day3 %>% 
  mutate(hill = gsub("\\.", 0, hill),
         hill = gsub("#", 1, hill))

day3_split <- sapply(day3$hill, str_extract_all, "\\d")
day3_split <- do.call("rbind", day3_split) %>% 
  as_tibble()


max <- dim(day3_split)[1]

tree_num <- lapply(1:max, function(row){
  column <- ((row - 1) * 3 + 1) %% 31
  if (column == 0) {column = 31}
  return(as.numeric(day3_split[row, column]))
})

do.call("sum", tree_num)

```

##Part 2

```{r}
max <- dim(day3_split)[1]
right <- c(seq(1,7,by = 2), 1)
down <- c(1,1,1,1,2)


slope_sum <- function(row, down, right){
   row_adjust <- (row - 1) * down + 1
    column <- ((row - 1) * right + 1) %% 31
    if (column == 0) {column = 31}
    return(as.numeric(day3_split[row_adjust, column]))
}

nums <- mapply(function(down, right){
  tree_num <- lapply(1:ceiling(max/down), slope_sum, down = down, right = right) 
  return(do.call("sum", tree_num))
}, down, right)

prod(nums)


```

#Day 4

##Part 1

```{r}
day4 <- read_file("data/day4.txt")


day4 <- day4 %>% str_extract_all(regex(r'{(^.+$(\r\n)?)+}', multiline = TRUE))
day4 <- day4[[1]]
  

passport = 1:length(day4)

day4_codes_list <- lapply(passport, function(iter){
    strsplit(day4[iter], ":|\r\n| ") %>% 
    unlist() %>% 
    matrix(ncol = 2, byrow = T) %>% 
    as_tibble() %>% 
    mutate(id = iter)
})

day4_codes <- do.call("rbind", day4_codes_list) %>% 
  pivot_wider(id_cols = id,
              names_from = V1,
              values_from = V2)

day4_valid <- day4_codes %>% 
  select(-cid) %>% 
  na.omit()

dim(day4_valid)

```

```{r}
day4_valid_2 <- day4_valid %>% 
  separate(hgt, into = c("hgt", "units"), sep = "(?<=[0-9])(?=[a-z])") %>% 
  na.omit() %>% 
  mutate(
    byr = as.numeric(byr),
    iyr = as.numeric(iyr),
    eyr = as.numeric(eyr),
    hgt = as.numeric(hgt)
  )

present <- 1:dim(day4_valid_2)[1]
num_valid <- lapply(present, function(iter){
  byr <- day4_valid_2$byr[iter] >= 1920 & day4_valid_2$byr[iter] <= 2002
  iyr <- day4_valid_2$iyr[iter] >= 2010 & day4_valid_2$iyr[iter] <= 2020
  eyr <- day4_valid_2$eyr[iter] >= 2020 & day4_valid_2$eyr[iter] <= 2030
  if(day4_valid_2$units[iter] == "cm"){
    hgt <- day4_valid_2$hgt[iter] >= 150 & day4_valid_2$hgt[iter] <= 193
  } else{if (day4_valid_2$units[iter] == "in"){
    hgt <- day4_valid_2$hgt[iter] >= 59 & day4_valid_2$hgt[iter] <= 76
  } else{
    hgt <- FALSE
  }
  }
  hcl <- grepl("#[0-9A-Fa-f]", day4_valid_2$hcl[iter])
  ecl <- day4_valid_2$ecl[iter] %in% c("amb", "blu", "brn", "gry", "grn", "hzl", "oth")
  pid <- grepl("^[0-9]{9}$", day4_valid_2$pid[iter])
  if (byr & iyr & eyr & hgt & hcl & ecl & pid){
    return (1)
  } else {
    return(0)
  }
})
do.call("sum", num_valid)
```

